### ISSUE TITLE
Cannot test with it

### ISSUE THREAD

**Issue by cperezabo** [Enngage/ngx-captcha#27]
It runs normally on `ng serve`, but it fails on `ng test`.
I always get `TypeError: this.reCaptchaApi.render is not a function` in test case, and `TypeError: this.reCaptchaApi.render is not a function` in Chrome console.

**Comment by Enngage** [comment]
Can you provide more details? Code example? Repro?

**Comment by cperezabo** [comment]
component's template
```html
<ngx-recaptcha2
          [siteKey]="reCaptchaSiteKey"
          hl="es"
          formControlName="recaptcha">
</ngx-recaptcha2>
```

In the spect I have this

```typescript
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        ReactiveFormsModule,
      ],
      declarations: [
        FormRegistroEmailComponent,
        ReCaptcha2Component,
      ],
      providers: [
        {
          provide: environment.reCaptchaSiteKey,
          useValue: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI',
        },
        {
          provide: RegistroService,
          useValue: registroServiceStub,
        }
      ]
    })
      .compileComponents();
  }));
```

I cannot provide more code because It just fails in every `it` with the error I mention... It is like the google api is not loaded in reCaptchaApi and so the render method doesn't exist

**Comment by Enngage** [comment]
I can't say really, but testing should work in general (once the timeout issue is solved) as is discussed here -> https://github.com/Enngage/ngx-captcha/issues/26

**Comment by Enngage** [comment]
Does it work with the new version? `5.0.4`?

**Comment by cperezabo** [comment]
Getting same errors with 5.0.4

<img width="966" alt="captura de pantalla 2018-10-03 a la s 13 14 28" src="https://user-images.githubusercontent.com/3604722/46424078-83d45380-c70e-11e8-8190-c819ad9d542b.png">
<img width="553" alt="captura de pantalla 2018-10-03 a la s 13 15 58" src="https://user-images.githubusercontent.com/3604722/46424084-859e1700-c70e-11e8-82ea-b18e2bc46fca.png">

**Comment by Enngage** [comment]
Looking back at this error, it seems like the google script is not loaded. I'm not sure how this could happen or why, but your tests should expose google api. By default, I'm adding google script on component init, but maybe your test doesn't run in the same context or clears global variables (which the google script is). 

This should be solved by adding google script to your tests globally if they cannot be loaded by component on init.

**Comment by gkovacs81** [comment]
I have the same problem. Could you please take a look into it?

Repo: https://github.com/ArPIHomeSecurity/www
Travis build: https://travis-ci.org/ArPIHomeSecurity/www

**Comment by gkovacs81** [comment]
Thanks @Enngage! Finally I found the solution based on https://github.com/Enngage/ngx-captcha/issues/27#issuecomment-436538261!
If anyone's interested the solution is in commit: https://github.com/ArPIHomeSecurity/www/commit/91d81df82a067a736f61e0546a4c4a588259cfe0

**Comment by Enngage** [comment]
Thank you @gkovacs81 , I'll be having a further look at this and possibly add it to documentation as well !
